name: Send Email via Postfix - ARC

permissions:
  contents: write

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  send-email:
    runs-on: arc-runner-set
    steps:

      - name: Set up Postfix
        run: |
          sudo apt-get update
          sudo apt-get install -y postfix msmtp

      - name: Configure Postfix
        run: |
          # Set your hostname for Postfix
          sudo postconf -e 'myhostname = github-actions.${{ secrets.MAIL_DOMAIN }}'
          sudo postconf -e 'mydomain  = ${{ secrets.MAIL_DOMAIN }}'
          sudo postconf -e 'myorigin  = ${{ secrets.MAIL_DOMAIN }}'
          echo "runner yuriy.plo@gmail.com" | sudo tee /etc/postfix/generic
          sudo postmap /etc/postfix/generic
          sudo postconf -e 'smtp_generic_maps = hash:/etc/postfix/generic'
          echo "[smtp.gmail.com]:587 ${{ secrets.MAIL_USERNAME }}:${{ secrets.MAIL_PASSWORD }}" | sudo tee /etc/postfix/sasl_passwd
          sudo postmap /etc/postfix/sasl_passwd
          sudo postconf -e 'maillog_file = /var/log/mail.log'
          sudo touch /var/log/mail.log
          sudo service postfix start

      - name: Create HTML email content
        run: |
          cat <<EOM > email.html
          <html>
          <head><title>Test HTML Email</title></head>
          <body>
          <p>New Netbox images have been built and pushed to Docker HUB.</p>
          <p>The latest version of Netbox is: <strong>TEST</strong></p>
          <p>The Docker image tag is: <strong>TEST/nettools:netbox-TEST-build.TEST</strong></p>
          </body>
          </html>
          EOM

      - name: Send email to multiple recipients
        run: |
          # Retrieve the secret containing the email addresses
          emails=" ${{ secrets.MAIL_TO }}"

          # Split the emails by semicolon
          IFS=';' read -r -a email_array <<< "$emails"

          # Loop through the array of email addresses and send the email
          for recipient in "${email_array[@]}"; do
            (echo "To: $recipient"; 
             echo "Subject: Test HTML Email"; 
             echo "MIME-Version: 1.0"; 
             echo "Content-Type: text/html; charset=UTF-8"; 
             echo ""; 
             cat email.html) | sendmail -v -t
            echo "Sent email to $recipient"
          done

      - name: Check Postfix Mail Log
        run: |
          sudo cat /var/log/mail.log

      - name: Check Postfix Mail Queue
        run: |
          mailq
          
          
