name: Send Email via Postfix - ARC

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: arc-runner-set
    steps:

      - name: Set up MSMTP
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp msmtp-mta

      - name: Configure MSMTP
        run: |
          cat << 'EOF' > .msmtprc
            account office365
            host smtp.office365.com
            port 587
            domain ${{ secrets.MAIL_DOMAIN }}
            from ${{ secrets.MAIL_FROM }}
            user ${{ secrets.MAIL_USERNAME }}
            password ${{ secrets.MAIL_PASSWORD }}
            tls on
            auth on
            logfile .msmtp.log
          EOF
          chmod 600 .msmtprc

      - name: Create HTML email content
        run: |
          cat << 'EOF' > email.html
          Subject: Your Email Subject
          Content-Type: text/html; charset=UTF-8
          To: ${{ secrets.MAIL_TO }}
          
          <html>
            <body>
              <p>New Netbox images have been built and pushed to Docker HUB.</p>
              <p>The latest version of Netbox is: <strong>${{ needs.check_docker_hub.outputs.latest_tag }}</strong></p>
              <p>The Docker image tag is: <strong>${{ secrets.DOCKERHUB_USERNAME }}/nettools:netbox-${{ needs.check_docker_hub.outputs.latest_tag }}-build.${{ steps.tag_timestamp.outputs.timestamp }}</strong></p>
          </body>
          </html>

          EOF