name: Send Email via Postfix - ARC

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: arc-runner-set
    steps:

      - name: Set up MSMTP
        run: |
          sudo apt-get update
          sudo apt-get install -y msmtp msmtp-mta

      - name: Configure MSMTP
        run: |
          cat <<EOM > .msmtprc
            account office365
            host smtp.office365.com
            port 587
            domain ${{ secrets.MAIL_DOMAIN }}
            from ${{ secrets.MAIL_FROM }}
            user ${{ secrets.MAIL_USERNAME }}
            password ${{ secrets.MAIL_PASSWORD }}
            tls on
            auth on
            logfile .msmtp.log
          EOM
          chmod 600 .msmtprc

      - name: Create HTML email content
        run: |
          cat << EOM > email.html
            Subject: Your Email Subject from Github Action ARC
            Content-Type: text/html; charset=UTF-8
            To: yuriy.plo@gmail.com
          
            <html>
              <body>
                <p>New Netbox images have been built and pushed to Docker HUB.</p>
                <p>The latest version of Netbox is: <strong>TEST</strong></p>
                <p>The Docker image tag is: <strong>TEST/nettools:netbox-TEST-build.TEST</strong></p>
              </body>
            </html>
          EOM

      - name: Debug 1
        run: |
          pwd
          cat .msmtprc

      - name: Debug 2
        run: |
          pwd
          cat email.html
      - name: Send Email
        run: |
          msmtp -a office365 -C .msmtprc -t < email.html

      - name: Debug logs
        run: |
          cat .msmtp.log

          
          
