name: A job to say hello

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: arc-runner-set-dind
#    container:
#      image: ubuntu:22.04  # You can use a different container image depending on your needs
#      options: --entrypoint ""  # Optional, use if you need to override the default entrypoint

    steps:
      - name: Hello world action step
        id: hello
        uses: YP-Docker/notify-with-mail@v1.0.1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
