name: Monitor Docker Hub for New Pushes

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch latest tags from Docker Hub
        id: fetch_tags
        run: |
          REPO="netboxcommunity/netbox"
          TAGS=$(curl -s "https://hub.docker.com/v2/repositories/$REPO/tags/" | jq -r '.results[].name')
          echo "Latest tags: $TAGS"
          echo "::set-output name=tags::$TAGS"

      - name: Check for new tags
        run: |
          echo "Comparing tags to previously known tags..."
          # You can add logic here to compare tags and act on new ones.

      - name: Debug - Display fetched tags
        run: |
          echo "Fetched tags: ${{ steps.fetch_tags.outputs.tags }}"
