name: Manual Test Execution
on:
  workflow_dispatch:
    inputs:
      testType:
        description: 'Type of tests to run'
        required: true
        default: 'integration'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Tests
        run: npm run test -- --type ${{ github.event.inputs.testType }}
